import { User, Task, TimeEntry, ScheduleShift, Conversation, Message, DashboardSummary, Notification } from '@/types';

export const mockUser: User = {
  id: 'emp-001',
  email: 'john.doe@company.com',
  fullName: 'John Doe',
  phone: '+1 (555) 123-4567',
  jobTitle: 'Field Technician',
  department: 'Operations',
  company: 'Apex Solutions Inc.',
  role: 'employee',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
};

export const mockTasks: Task[] = [
  {
    id: 't-001',
    title: 'Complete site inspection at Building A',
    description: 'Perform a full safety inspection of Building A, including fire exits, electrical panels, and HVAC systems. Document all findings and submit report.',
    status: 'in_progress',
    priority: 'high',
    assignedDate: '2026-02-20',
    dueDate: '2026-02-25',
    notes: ['Checked fire exits - all clear', 'Electrical panel B needs follow-up'],
    images: [],
    category: 'Inspection',
  },
  {
    id: 't-002',
    title: 'Submit weekly progress report',
    description: 'Compile and submit the weekly progress report covering all completed tasks and ongoing projects.',
    status: 'pending',
    priority: 'medium',
    assignedDate: '2026-02-22',
    dueDate: '2026-02-28',
    notes: [],
    images: [],
    category: 'Report',
  },
  {
    id: 't-003',
    title: 'Equipment maintenance - Sector 7',
    description: 'Perform scheduled maintenance on all equipment in Sector 7. Replace filters and check calibration.',
    status: 'pending',
    priority: 'high',
    assignedDate: '2026-02-21',
    dueDate: '2026-02-26',
    notes: ['Parts ordered and received'],
    images: [],
    category: 'Maintenance',
  },
  {
    id: 't-004',
    title: 'Client meeting preparation',
    description: 'Prepare presentation materials for the upcoming client meeting. Include project updates and timeline.',
    status: 'completed',
    priority: 'medium',
    assignedDate: '2026-02-18',
    dueDate: '2026-02-22',
    notes: ['Slides completed', 'Reviewed by manager'],
    images: [],
    category: 'Meeting',
  },
  {
    id: 't-005',
    title: 'Update safety documentation',
    description: 'Review and update all safety documentation for Q1 compliance requirements.',
    status: 'completed',
    priority: 'low',
    assignedDate: '2026-02-15',
    dueDate: '2026-02-20',
    notes: ['All docs updated', 'Submitted to compliance'],
    images: [],
    category: 'Documentation',
  },
  {
    id: 't-006',
    title: 'Install new monitoring sensors',
    description: 'Install 12 new environmental monitoring sensors across the main facility floor.',
    status: 'pending',
    priority: 'medium',
    assignedDate: '2026-02-23',
    dueDate: '2026-03-01',
    notes: [],
    images: [],
    category: 'Installation',
  },
];

export const mockTimeEntries: TimeEntry[] = [
  {
    id: 'te-001',
    date: '2026-02-24',
    clockIn: '2026-02-24T08:02:00',
    clockOut: null,
    totalHours: null,
    status: 'clocked_in',
  },
  {
    id: 'te-002',
    date: '2026-02-23',
    clockIn: '2026-02-23T07:58:00',
    clockOut: '2026-02-23T16:32:00',
    totalHours: 8.57,
    status: 'clocked_out',
  },
  {
    id: 'te-003',
    date: '2026-02-22',
    clockIn: '2026-02-22T08:15:00',
    clockOut: '2026-02-22T17:00:00',
    totalHours: 8.75,
    status: 'clocked_out',
  },
  {
    id: 'te-004',
    date: '2026-02-21',
    clockIn: '2026-02-21T08:00:00',
    clockOut: '2026-02-21T16:45:00',
    totalHours: 8.75,
    status: 'clocked_out',
  },
  {
    id: 'te-005',
    date: '2026-02-20',
    clockIn: '2026-02-20T07:50:00',
    clockOut: '2026-02-20T16:20:00',
    totalHours: 8.5,
    status: 'clocked_out',
  },
];

export const mockSchedule: ScheduleShift[] = [
  {
    id: 'sh-001',
    date: '2026-02-24',
    startTime: '08:00',
    endTime: '17:00',
    location: 'Main Facility - Building A',
    role: 'Field Technician',
    tasks: ['Site inspection', 'Equipment check'],
  },
  {
    id: 'sh-002',
    date: '2026-02-25',
    startTime: '08:00',
    endTime: '17:00',
    location: 'Warehouse B',
    role: 'Field Technician',
    tasks: ['Sensor installation', 'Maintenance'],
  },
  {
    id: 'sh-003',
    date: '2026-02-26',
    startTime: '09:00',
    endTime: '18:00',
    location: 'Client Office - Downtown',
    role: 'Field Technician',
    tasks: ['Client meeting', 'Progress review'],
  },
  {
    id: 'sh-004',
    date: '2026-02-27',
    startTime: '08:00',
    endTime: '16:00',
    location: 'Main Facility - Sector 7',
    role: 'Field Technician',
    tasks: ['Equipment maintenance'],
  },
  {
    id: 'sh-005',
    date: '2026-02-28',
    startTime: '08:00',
    endTime: '17:00',
    location: 'Main Facility - Building A',
    role: 'Field Technician',
    tasks: ['Weekly report', 'Documentation'],
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-001',
    participantName: 'Sarah Mitchell',
    participantRole: 'Operations Manager',
    participantAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    lastMessage: 'Please update the inspection report by EOD.',
    lastMessageTime: '2026-02-24T10:30:00',
    unreadCount: 2,
  },
  {
    id: 'conv-002',
    participantName: 'Mike Rodriguez',
    participantRole: 'Team Lead',
    participantAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    lastMessage: 'The parts for Sector 7 maintenance are ready.',
    lastMessageTime: '2026-02-24T09:15:00',
    unreadCount: 0,
  },
  {
    id: 'conv-003',
    participantName: 'HR Department',
    participantRole: 'Human Resources',
    lastMessage: 'Your onboarding documents have been approved.',
    lastMessageTime: '2026-02-23T14:00:00',
    unreadCount: 1,
  },
];

export const mockMessages: Record<string, Message[]> = {
  'conv-001': [
    {
      id: 'msg-001',
      senderId: 'mgr-001',
      senderName: 'Sarah Mitchell',
      content: 'Hi John, how is the Building A inspection going?',
      timestamp: '2026-02-24T09:00:00',
      read: true,
      conversationId: 'conv-001',
    },
    {
      id: 'msg-002',
      senderId: 'emp-001',
      senderName: 'John Doe',
      content: 'Going well! Fire exits are all clear. Working on electrical panels now.',
      timestamp: '2026-02-24T09:15:00',
      read: true,
      conversationId: 'conv-001',
    },
    {
      id: 'msg-003',
      senderId: 'mgr-001',
      senderName: 'Sarah Mitchell',
      content: 'Great progress. Please update the inspection report by EOD.',
      timestamp: '2026-02-24T10:30:00',
      read: false,
      conversationId: 'conv-001',
    },
    {
      id: 'msg-004',
      senderId: 'mgr-001',
      senderName: 'Sarah Mitchell',
      content: 'Also, make sure to document any issues with photos.',
      timestamp: '2026-02-24T10:31:00',
      read: false,
      conversationId: 'conv-001',
    },
  ],
  'conv-002': [
    {
      id: 'msg-005',
      senderId: 'lead-001',
      senderName: 'Mike Rodriguez',
      content: 'Hey John, just letting you know the parts for Sector 7 maintenance are ready for pickup.',
      timestamp: '2026-02-24T09:15:00',
      read: true,
      conversationId: 'conv-002',
    },
  ],
  'conv-003': [
    {
      id: 'msg-006',
      senderId: 'hr-001',
      senderName: 'HR Department',
      content: 'Your onboarding documents have been approved. Welcome aboard!',
      timestamp: '2026-02-23T14:00:00',
      read: false,
      conversationId: 'conv-003',
    },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 'n-001',
    title: 'New Task Assigned',
    message: 'You have been assigned "Install new monitoring sensors"',
    type: 'task',
    read: false,
    timestamp: '2026-02-24T08:00:00',
  },
  {
    id: 'n-002',
    title: 'Schedule Update',
    message: 'Your shift on Feb 26 has been updated to 9:00 AM - 6:00 PM',
    type: 'schedule',
    read: false,
    timestamp: '2026-02-23T16:00:00',
  },
  {
    id: 'n-003',
    title: 'Message from Sarah Mitchell',
    message: 'Please update the inspection report by EOD.',
    type: 'message',
    read: true,
    timestamp: '2026-02-24T10:30:00',
  },
];

export const mockDashboard: DashboardSummary = {
  totalTasks: 6,
  pendingTasks: 3,
  inProgressTasks: 1,
  completedTasks: 2,
  isClockedIn: true,
  todayHours: 4.5,
  weeklyHours: 39.07,
  unreadMessages: 3,
  upcomingShifts: 5,
  notifications: mockNotifications,
};
